### ISSUE TITLE
Mem split not working

### ISSUE THREAD

**Issue by lupin-de-mid** [mikolak-net/ansible-raspi-config#13]
This playbok fail on raspberry 3
```
- hosts: pi
  become: true
  roles: 
    - role: mikolak.raspi-config
      raspi_config_memory_split_gpu: 16
      raspi_config_update_packages: yes
      raspi_config_expanded_filesystem: yes
      raspi_config_ensure_optimal_cpu_params: yes
      raspi_config_enable_camera: 

```

> 
> TASK [mikolak.raspi-config : ensure mem split] **********************************************************************************************************************
> fatal: [pi3]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.2.176 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_qn6m9xwt/ansible_module_pi_boot_config.py\", line 88, in <module>\r\n    main()\r\n  File \"/tmp/ansible_qn6m9xwt/ansible_module_pi_boot_config.py\", line 72, in main\r\n    config_vals = dict((str(key), str(val)) for (key, val) in config_vals.iteritems())\r\nAttributeError: 'dict' object has no attribute 'iteritems'\r\n", "msg": "MODULE FAILURE", "rc": 0}

**Comment by mikolak-net** [comment]
Looks like a Ansible version syntax regression. Thanks for reporting it, I'll add it to the next release (should be sometime in February).

**Comment by colin-nolan** [comment]
@mikolak-net it's ude to a change in `dict` in Python 3 - it no longer has the `iteritems` method. See: http://legacy.python.org/dev/peps/pep-3106/.

**Comment by mikolak-net** [comment]
Ah, you're right, thanks!

**Comment by lupin-de-mid** [comment]
Maybe you have any updates about upcoming release

**Comment by mikolak-net** [comment]
Yup, should be this week finally, needed some SD cards for testing and kept forgetting to order them, sorry about that.

**Comment by mikolak-net** [comment]
@lupin-de-mid : fix is in master. Unfortunately I can't find an unused Pi3 to test on, so may I ask you to verify whether it works for you? You can add the role from GitHub via defining it in your `requirements.yml` like this:

```yaml
- src: "https://github.com/mikolak-net/ansible-raspi-config"
  name: mikolak.raspi-config
  version: 28ce300bf97c09032502706e2138df5a8d60d108
```
